# Auth服务Dockerfile
FROM eclipse-temurin:17-jre-alpine

LABEL maintainer="changzheng"

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app
RUN addgroup -S app && adduser -S -G app app
COPY --chown=app:app changzheng-auth/target/changzheng-auth-1.0.0.jar app.jar
USER app

EXPOSE 8081

ENTRYPOINT ["java", "-Xms256m", "-Xmx512m", "-jar", "app.jar"]
